limits:
  z: [ -4., 8. ]
  r: [ 0., 4. ]
  max_field: [ 1., 1. ]
  power_p: [ 1., 1. ]
  coefficient_K0: [ 0, 0. ]
  collision_frequency: [ 0.0, 0.0 ]

torch:
  device: 'cuda'
  dtype: 'torch.float32'
  seed: 1234

data:
  num_of_points:
    eq: 96000
    bc: 96000
    ic: 96000
  batch_size:
    train: 32000
    test: 64

model:
  trunk:
    hidden_layers: 3
    hidden_features: 128
  branch:
    hidden_layers: 3
    hidden_features: 128
  mixer:
    in_features: 96

  fourier_features: 64
  bessel_features: 32
